<%@ Page Title="Dorknozzle Address Book" 
         Language="C#" 
         MasterPageFile="~/Dorknozzle.Master" 
         AutoEventWireup="true" 
         Inherits="Dorknozzle.AddressBook" 
         CodeFile="AddressBook.aspx.cs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Address Book</h1>

    <p>
        <asp:LinkButton ID="addEmployeeButton" runat="server" Text="Add New Employee" OnClick="addEmployeeButton_Click" />
    </p>

    <asp:GridView ID="grid" 
        runat="server" 
        AutoGenerateColumns="False" AllowPaging="True" AllowSorting="True" DataKeyNames="EmployeeID" DataSourceID="employeesDataSource" PageSize="3" >
        <Columns>
          <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
          <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
          <asp:BoundField DataField="MobilePhone" HeaderText="Mobile Phone" />
          <asp:ButtonField CommandName="Select" Text="Select" />
        </Columns>
    </asp:GridView>
    
    <br />

    <%--<asp:Label ID="detailsLabel" runat="server" />--%>
    <asp:DetailsView ID="employeeDetails" 
                     runat="server" 
                     AutoGenerateRows="False" 
                     AutoGenerateDeleteButton="True" 
                     AutoGenerateEditButton="True" 
                     AutoGenerateInsertButton="True" 
                     DataSourceID="employeeDataSource" 
                     DataKeyNames="EmployeeID">
        <Fields>
            <asp:BoundField DataField="EmployeeID" 
                            HeaderText="EmployeeID" 
                            SortExpression="EmployeeID" 
                            InsertVisible="False" 
                            ReadOnly="True" />

            <%--<asp:BoundField DataField="DepartmentID" HeaderText="DepartmentID" SortExpression="DepartmentID" />--%>
            <asp:TemplateField HeaderText="Department" SortExpression="DepartmentID">
                <EditItemTemplate>
                    <asp:DropDownList ID="didDdl" 
                        runat="server"  
                        DataSourceID="departmentsDataSource" 
                        DataTextField="Department" 
                        DataValueField="DepartmentID"
                        SelectedValue='<%# Bind("DepartmentID") %>'/>
                </EditItemTemplate>

                <InsertItemTemplate>
                    <asp:DropDownList ID="didDdl" 
                        runat="server"  
                        DataSourceID="departmentsDataSource" 
                        DataTextField="Department" 
                        DataValueField="DepartmentID"
                        SelectedValue='<%# Bind("DepartmentID") %>'/>
                </InsertItemTemplate>

                <ItemTemplate>
                    <asp:DropDownList ID="didDdl" 
                        runat="server"  
                        DataSourceID="departmentsDataSource" 
                        DataTextField="Department" 
                        DataValueField="DepartmentID"
                        SelectedValue='<%# Bind("DepartmentID") %>' 
                        Enabled="False" />
                </ItemTemplate>
            </asp:TemplateField>

            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />

            <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />

            <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />

            <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />

            <%--<asp:TemplateField HeaderText="Address">
                <EditItemTemplate>
                    <asp:TextBox ID="editAddressTextBox" runat="server" Text='<%# Bind("Address") %>'></asp:TextBox>
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:TextBox ID="insertAddressTextBox" runat="server" Text='<%# Bind("Address") %>'></asp:TextBox>
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="addressLabel" runat="server" Text='<%# Bind("Address") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>--%>

            <asp:BoundField DataField="City" HeaderText="City" />
            <%--<asp:TemplateField HeaderText="City">
                <EditItemTemplate>
                    <asp:TextBox ID="editCityTextBox" runat="server" Text='<%# Bind("City") %>'></asp:TextBox>
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:TextBox ID="insertCityTextBox" runat="server" Text='<%# Bind("City") %>'></asp:TextBox>
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="cityLabel" runat="server" Text='<%# Bind("City") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>--%>

            <asp:BoundField DataField="MobilePhone" HeaderText="MobilePhone" SortExpression="MobilePhone" />

            <asp:BoundField DataField="State" HeaderText="State" />
            <%--<asp:TemplateField HeaderText="State">
                <EditItemTemplate>
                    <asp:TextBox ID="editStateTextBox" runat="server" Text='<%# Bind("State") %>'></asp:TextBox>
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:TextBox ID="insertStateTextBox" runat="server" Text='<%# Bind("State") %>'></asp:TextBox>
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="stateLabel" runat="server" Text='<%# Bind("State") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>--%>

            <asp:BoundField DataField="Zip" HeaderText="Zip" />
            <%--<asp:TemplateField HeaderText="Zip">
                <EditItemTemplate>
                    <asp:TextBox ID="editZipTextBox" runat="server" Text='<%# Bind("Zip") %>'></asp:TextBox>
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:TextBox ID="insertZipTextBox" runat="server" Text='<%# Bind("Zip") %>'></asp:TextBox>
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="zipLabel" runat="server" Text='<%# Bind("Zip") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>--%>

            <asp:BoundField DataField="HomePhone" HeaderText="Home Phone" />
            <%--<asp:TemplateField HeaderText="Home Phone">
                <EditItemTemplate>
                    <asp:TextBox ID="editHomePhoneTextBox" runat="server" Text='<%# Bind("HomePhone") %>'></asp:TextBox>
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:TextBox ID="insertHomePhoneTextBox" runat="server" Text='<%# Bind("HomePhone") %>'></asp:TextBox>
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="homePhoneLabel" runat="server" Text='<%# Bind("HomePhone") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>--%>

            <asp:BoundField DataField="Extension" HeaderText="Extension" />
            <%--<asp:TemplateField HeaderText="Extension">
                <EditItemTemplate>
                    <asp:TextBox ID="editExtensionTextBox" runat="server" Text='<%# Bind("Extension") %>'></asp:TextBox>
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:TextBox ID="insertExtensionTextBox" runat="server" Text='<%# Bind("Extension") %>'></asp:TextBox>
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="extensionLabel" runat="server" Text='<%# Bind("Extension") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>--%>

            <%--<asp:CommandField ShowEditButton="True" />--%>
        </Fields>

        <HeaderTemplate>
            <%#Eval("Name") == null ? "Adding New Employee" : Eval("Name") %>
        </HeaderTemplate>
    </asp:DetailsView>

    <asp:SqlDataSource ID="employeesDataSource" 
                       runat="server" 
                       ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
                       SelectCommand="SELECT [EmployeeID], [Name], [City], [MobilePhone] FROM [Employees] ORDER BY [Name]">
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="employeeDataSource" 
                       runat="server" 
                       ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
                       DeleteCommand="DELETE FROM [Employees] WHERE [EmployeeID] = @EmployeeID" 
                       InsertCommand="INSERT INTO [Employees] ([DepartmentID], [Name], [Username], [Password], [Address], [State], [City], [Zip], [HomePhone], [Extension], [MobilePhone]) VALUES (@DepartmentID, @Name, @Username, @Password, @Address, @State, @City, @Zip, @HomePhone, @Extension, @MobilePhone)" 
                       SelectCommand="SELECT [EmployeeID], [DepartmentID], [Name], [Username], [Password], [Address], [State], [City], [Zip], [HomePhone], [Extension], [MobilePhone] FROM [Employees] WHERE ([EmployeeID] = @EmployeeID)" 
                       UpdateCommand="UPDATE [Employees] SET [DepartmentID] = @DepartmentID, [Name] = @Name, [Username] = @Username, [Password] = @Password, [Address] = @Address, [State] = @State, [City] = @City, [Zip] = @Zip, [HomePhone] = @HomePhone, [Extension] = @Extension, [MobilePhone] = @MobilePhone WHERE [EmployeeID] = @EmployeeID">
        <DeleteParameters>
            <asp:Parameter Name="EmployeeID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="DepartmentID" Type="Int32" />
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="State" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="Zip" Type="String" />
            <asp:Parameter Name="HomePhone" Type="String" />
            <asp:Parameter Name="Extension" Type="String" />
            <asp:Parameter Name="MobilePhone" Type="String" />
        </InsertParameters>
        <SelectParameters>
            <asp:ControlParameter ControlID="grid" Name="EmployeeID" PropertyName="SelectedValue" Type="Int32" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="DepartmentID" Type="Int32" />
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="State" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="Zip" Type="String" />
            <asp:Parameter Name="HomePhone" Type="String" />
            <asp:Parameter Name="Extension" Type="String" />
            <asp:Parameter Name="MobilePhone" Type="String" />
            <asp:Parameter Name="EmployeeID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="departmentsDataSource" 
                       runat="server" 
                       ConnectionString="<%$ ConnectionStrings:Dorknozzle %>" 
                       SelectCommand="SELECT [DepartmentID], [Department] FROM [Departments]">
    </asp:SqlDataSource>
</asp:Content>
