<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Hello.aspx.cs" Inherits="P30.Hello" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Welcome to Build Your Own ASP.NET 3.5 Web Site!</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <p>Hello there!</p>

            <p>
                The time is now:
                <%-- Display the current date and time --%>
                <asp:Label ID="myTimeLabel" runat="server" />
            </p>

            <p>
                <% string Title = "This is generated by a code render block."; %>
                <%= Title %>
            </p>
        </div>
    </form>
</body>
</html>
